version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 80:80
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=onlinemarkets"
      - "MYSQL_USER=gom"
      - "MYSQL_PASSWORD=gom"
      - "MYSQL_ROOT_PASSWORD=gom"
    ports:
        - "33061:3306"
  myadmin:
    image: phpmyadmin/phpmyadmin
    links: 
        - database:db
    ports:
        - 8080:80
    environment:
        MYSQL_USER: gom
        MYSQL_PASSWORD: gom
        MYSQL_ROOT_PASSWORD: gom
volumes:
  dbdata: